name: Send Email Reminders

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Log current time
        run: date -u

      - name: Call reminders API
        run: |
          curl -X GET "${{ secrets.NEXT_PUBLIC_PROD_URL }}/api/reminders" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
