name: Send Email Reminders for Missing Lessons

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00 UTC
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Log current time
        run: date -u # Logs the current UTC time

      - name: Call reminders API
        run: curl -X GET "${{ secrets.NEXT_PUBLIC_PROD_URL }}/api/reminders"
